### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by willfarrell** [gordonfn/datastream-api-public#1]
## WO Scope

- Design Endpoint structure (1.5w)
  - url struct for data
  - rolling version changes
  - API style REST/grapghql/etc
  - response data structure (json, xml, geojson, geobuf, protobuf)
- security (1.5w)
  - authorization (cognito)
    - JWT w/ referrer domain
    - api key w/ whitelist ips
  - role based ACL (just a hook)
  - use analytics (req count, obj count)
- Implementation (3w)
  - config w/ terraform / serverless
  - APIG + lambda / ALB + fargate / HTTP APIG + lambda / CloudFlare + lambda
  - write logic & DB queries (mostly existing)
  - caching strategy
- documentation (auto generate) (1w)
  - must include swagger export
- performance (2w)
  - middleware optimizations
  - infrastructure optimizations
  - SQL optimizations

## Phase I
- Endpoints (OData v4)
  - metadata
    - geo id
    - dataset ids
    - organization name (future)
    - license (future)
  - locations
    - geo id
    - dataset ids
    - organization name (future)
  - observations
    - geo id
    - dataset ids
    - characteristic (future)
    - start/end year (fututre)
  - add observations (future)

## Endpoints
- datasets
- locations (name, lat, lng, mapcode)
- samples (dataset values, normailizations, ccme) (restrict parameters? no)
- don't use cloudfront? https://forum.serverless.com/t/directly-proxying-lambda-via-cloudfront-without-api-gateway/3808/23
- protocol testing: https://evertpot.com/h2-parallelism/
- release cycle - https://engineering.shopify.com/blogs/engineering/shopify-manages-api-versioning-breaking-changes

Ref:
- https://expeditedsecurity.com/api-security-best-practices-megaguide/
- https://www.trek10.com/blog/fargate-lambda-comparison/
- https://lumigo.io/blog/how-to-optimize-aws-lambda-performance/
- https://www.slappforge.com/blog/3-things-to-consider-when-designing-a-serverless-api

Survey: https://docs.google.com/forms/d/1GaWBmWyOTX8pnCeR30zFof1qLUh16_6uZnfyf9LOviM/edit#responses

## Browser
- [x] domain whitelisting
- [x] API Key
- [ ] tiles
  - locations
  - samples

## Server to Server
- [x] API Key
- [ ] ip whitelisting

## Features
- [x] API key expires yearly
- [x] request throttling / limit (total, rate) *
- [x] bandwidth throttling / limit *
- [x] limit by tenant/geojson, charaterictic
- [ ] move from serverless to terraform

* In lue of applying artificial limits, log everything and just charge for overages
## SLA
- [ ] documentation (swagger)
- [ ] OSS (schema, validation)
- [ ] semver changelog
- [ ] migration windows (3m?)
- [ ] request concurency 
- [ ] caching and cache-control

## Deps & strategies
- terraform each lambda
- lerna
  - rollup each lambda
  - middy for middleware
- replace `pg ` with `postgres` - https://github.com/porsager/postgres

## Refs
- https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md
- jsonapi
- odata
- https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api
- versioning - https://stripe.com/docs/api/versioning
